// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAllMessages = `-- name: ClearAllMessages :exec
DELETE FROM messages
`

func (q *Queries) ClearAllMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllMessages)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    user_id, content
) VALUES (
             $1, $2
         )
RETURNING id, user_id, content, created_at
`

type CreateMessageParams struct {
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT
    m.id,
    m.content,
    m.created_at,
    u.id AS user_id,
    u.username
FROM messages m
         JOIN users u ON m.user_id = u.id
ORDER BY m.created_at DESC
LIMIT $1
`

type GetRecentMessagesRow struct {
	ID        int64              `json:"id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    int64              `json:"user_id"`
	Username  string             `json:"username"`
}

func (q *Queries) GetRecentMessages(ctx context.Context, limit int32) ([]GetRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, getRecentMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMessagesRow
	for rows.Next() {
		var i GetRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
